### PR TITLE
Add Font Awesome support

### PR DESCRIPTION
**Pull request by lawgsy**
See also https://github.com/KELiON/cerebro-ui/pull/4

Usage (when added to cerebro-ui as well):
```
display({
  ...
  icon: 'fa-link',
  ...
}
```
where `fa-link` is the corresponding font-awesome icon you want to appear in the results list.

In a preview pane you can use the following instead:
```
import FontAwesome from 'react-fontawesome'
...
return <FontAwesome
              name="fa-link"
              size="2x"
              className='' />
```
Where the return statement is just returning a component as usual.

See https://www.npmjs.com/package/react-fontawesome

### CODE REVIEW

**Comment by lawgsy** [comment]
I just realized I might not have run the testing locally. We'll see how the CI goes

**Comment by lawgsy** [comment]
This seems to me as a temporary connection issue on github/yarn's side. Could you trigger a rebuild to see if the problem persists?

**Comment by lawgsy** [comment]
I can't build the latest master on this computer, let alone with my PR. Best not to merge this until I can verify it all works.

**Comment by KELiON** [comment]
@lawgsy I left a comment about depency in [your PR](https://github.com/KELiON/cerebro-ui/pull/4) in cerebro-ui. After you add it to dependencies I'll bump version of cerebro-ui and merge this PR

**Comment by oguhpereira** [comment]
thanks for the pr, but be sorry for not being able to continue with him this moment

**Pull request closed without merging**
