### PR TITLE
fix: Electron Version too Old

### LINKED ISSUE #499: Electron Version too Old
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Fedora Workstation 31
- **Cerebro.app version**: 0.32
Dump when I try to start the appimg from CLI:
```
installed: X-AppImage-BuildId=847a0770-d98f-11a7-0ebd-e5b83ffea09e image: X-AppImage-BuildId=847a0770-d98f-11a7-0ebd-e5b83ffea09e
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/marco/.config/Cerebro/config.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at Object.get (/tmp/.mount_nnFS67/usr/bin/resources/app.asar/main.js:162:18)
    at Object.module.exports.Object.defineProperty.value (/tmp/.mount_nnFS67/usr/bin/resources/app.asar/main.js:642:24)
    at __webpack_require__ (/tmp/.mount_nnFS67/usr/bin/resources/app.asar/main.js:21:30)
    at /tmp/.mount_nnFS67/usr/bin/resources/app.asar/main.js:64:18
    at Object.<anonymous> (/tmp/.mount_nnFS67/usr/bin/resources/app.asar/main.js:67:10)
    at Object.<anonymous> (/tmp/.mount_nnFS67/usr/bin/resources/app.asar/main.js:3738:3)
    at Module._compile (module.js:571:32)

(cerebro:56588): Pango-ERROR **: 14:53:06.510: Harfbuzz version too old (1.3.1)

[1]    56588 trace trap (core dumped)  ./cerebro-0.3.2-x86_64\(1\).AppImage
```
## Issue
I'm trying to run cerebro from the App Image, but it didn't start from the shortcut 
then I tryed to run it from CLI and got the error above, looked around the 
internet and it seems that one package inside the image is not 
compatible with my system and it should be updated by the devs...
Is it correct? Is this a known issue? Is there any workaround?
Are there plans to support my distro?
Thanks for taking the time to read this.

### PR DESCRIPTION
**Pull request by oguhpereira**
Hi @KELiON ,

I change the version of the "electron" and fixed the error

"Harfbuzz version too old"

Closes #499

### CODE REVIEW

**Comment by Scupake** [comment]
Thank you for fixing this!
I can't test it cuz for some reason I can't compile this successfully, but thanks anyway!

**Comment by infixint943** [comment]
@oguhpereira Could you please provide an AppImage of the same, with the updates applied? Thanks.

**Comment by matfy** [comment]
Can you compile EXE of your version and upload it? 

I think it should be 0.3.4 (0.3.3 is [here](https://github.com/KELiON/cerebro/issues/496))

**Comment by oguhpereira** [comment]
@matfy I'm not able to compile the version!

**Comment by oguhpereira** [comment]
@yper51 @alefduarte can you validate for me?

**Review by yper51 — DISMISSED** [review]
Looks good!
One observation is that using electron-builder in such a high version implies having to increase the electron-updater version in "./app" to at least 4.0.0 which requires a node version greater than 10, a sudden change at first sight.
I suggest that a more subtle advance in electron-builder is going to be better, a version like "^19", so we can use version "^3" of the electron-updater and try to target the node version 10, which I was able to build from this commit.

**Comment by oguhpereira** [comment]
@yper51 I will close this pr to create one that affects all dependencies

**Pull request closed without merging**
