### PR TITLE
feat: migrate move file to native nodejs

### PR DESCRIPTION
**Pull request by oguhpereira**
I'm removing the move-file dependency and changing it to native. I believe this package is no longer needed.

### CODE REVIEW

**Comment by dubisdev** [comment]
Hi @oguhpereira 

I think move-file is more than a simple rename utility. It helps with creating recursive missing directories. We could migrate this to native but I think is a small dependency and does what we need.

https://bundlephobia.com/package/move-file@2.1.0 ➡️ Just 1.2kB


This PR is breaking scoped plugins installation

image

**Comment by dubisdev** [comment]
We could implement handling recursive directories (which is an additional work) or simply close this PR and continue using move-file

**Review by dubisdev — CHANGES_REQUESTED** [review]
- Implement native recursive rename
or
- Close the PR

**Comment by oguhpereira** [comment]
I have a negative question about the repository. It's not a very current repository, it hasn't been updated for a long time, I'm afraid it might hurt us for a moment.

I believe that if we are going to use it we should try to use at least the latest version, I tried here but it started to generate an error.

For the moment I will close the pr until I understand better how to proceed

**Pull request closed without merging**
