### PR TITLE
[BUILD]: updating Cerebro core

### LINKED ISSUE #426: Unable to compile on node v9, which blocks upgrading on Arch Linux
Arch Linux
yarn: 1.3.2
node: 9.2.0

---------------

Please follow **exactly** these steps (don't use repo that you had cloned before):

```
$ git clone https://github.com/KELiON/cerebro.git cerebro
$ cd cerebro
$ yarn
.....
$ cd app
$ yarn
```

Expected: both `yarn` runs succeed.
Actual: the second `yarn` fails.

```
❯ yarn
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.1: The platform "linux" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠄ ref:    ^~~~~~~~~~
[-/2] ⠄ waiting...
[-/2] ⠄ waiting...
[-/2] ⠄ waiting...
error /home/maximbaz/private/cerebro/app/node_modules/ref: Command failed.
Exit code: 1
..........
..........
..........
make: *** [binding.target.mk:95: Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/maximbaz/private/cerebro/app/node_modules/ref/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.13.12-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/maximbaz/private/cerebro/app/node_modules/ref
```

### LINKED ISSUE #467: window start error
I'am using 0.32 on win 10.
When i first start app, alert many errors.

After some work, I find code error at ``main.development.js``:
```js
let trayIconSrc = `${__dirname}/tray_icon.png`
if (process.platform === 'darwin') {
  trayIconSrc = `${__dirname}/tray_iconTemplate@2x.png`
} else if (process.platform === 'win32') {
  trayIconSrc = `${__dirname}/tray_icon.ico`
}
```

On windows, I think the path should be '\\' instead of '/'.

I use `asar` change file packged in app.asar, Evething is fine.

### LINKED ISSUE #489: No search results in Cerebro Windows
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **Windows 10**: 
- **Cerebro.app 0.3.1 **: 
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue

I just installed Cerebro on Windows 10 from cerebroapp but I'm unable to see any external apps/files in the results. I installed some plugins( spotify, calculator etc) but it still didn't work (The calculator is also not working)
Also, the app freezes on 'Manage plugins'. I had to install the plugins via cmd.

### LINKED ISSUE #528: update electron-update to recommend version
when i try to build from source. it tells me 

image

the version of electron-update is here

https://github.com/cerebroapp/cerebro/blob/251f4b0ac392ec577a5baae682a869a15812b99c/app/package.json#L21

### LINKED ISSUE #550: Build error Can't resolve 'spawn-sync'
- [X] I am on the [latest](https://github.com/cerebroapp/cerebro/releases/latest) Cerebro.app version
- [X] I have searched the [issues](https://github.com/cerebroapp/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 12.2.1 M1 Pro
- **Cerebro.app version**: Checkout from master (https://github.com/cerebroapp/cerebro/commit/606a1ba6f83f6268510001f98fc864e5816b67b2)
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue
I got failed build error, tried to update manually `execa` as mentioned from here https://github.com/sindresorhus/shell-env/issues/12
```
WARNING in ./node_modules/shell-env/node_modules/cross-spawn/index.js
Module not found: Error: Can't resolve 'spawn-sync' in '/Users/me/Project/cerebro/node_modules/shell-env/node_modules/cross-spawn'
 @ ./node_modules/shell-env/node_modules/cross-spawn/index.js 32:26-47
 @ ./node_modules/shell-env/node_modules/execa/index.js
 @ ./node_modules/shell-env/index.js
 @ ./node_modules/shell-path/index.js
 @ ./node_modules/fix-path/index.js
 @ ./app/background/background.js
 @ multi webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr ./app/background/background

```

### PR DESCRIPTION
**Pull request by dubisdev**
## Why

Cerebro build system is nowadays outdated: electron v13, babel v6, webpack v3... With this update Cerebro will get more recent dependencies, security updates, possible bug fixes...

## Pending tasks

- [x] Migrated to the last electron version
- [x] Migrated to webpack v4
- [x] Migrated to the last eslint version
- [x] Removed outdated dependencies
- [x] Created a GH flow for compiling the code for different platforms. (GH actions are free for open source projects!)
- [x] Configure test script (currently not working in v0.5.0, I deleted all mock files and I'll search for a solution)
- [x] Update package.json (I changed it to test GH action)
- [x] Update development docs about [two package.json structure](https://www.electron.build/tutorials/two-package-structure.html) and where to add dependencies.

## ⚠️ BREAKING CHANGES

- `remote` module is no longer available with electron v19. All plugins that were using this module will stop working. `@electron/remote` must me used instead.

  - [x] We must update [cerebro-basic-apps](https://github.com/cerebroapp/cerebro-basic-apps), which is currently not working well in v0.5.0 #555  and is using [remote module](https://github.com/cerebroapp/cerebro-basic-apps/blob/52083aefa3995405d08b2a1c3b7718393a0f842c/src/linux.js#L1)

## Possible related issues

- fix #467 
- fix #489 
- fix #550 
- fix #528 
- #552 
- fix #426 
- Includes #557 and #558

### CODE REVIEW

**Comment by dubisdev** [comment]
CI is now working well. This is a test release: https://github.com/dubisdev/cerebro/releases/tag/0.5.4

**Comment by dubisdev** [comment]
For now this is ready!
I'm now working in a PR to fix `cerebro-basic-apps`, but cerebro-ui also needs to be updated, so for now this is all here. Now I'll fix and update the plugins.


image

**Comment by dubisdev** [comment]
Just opened https://github.com/cerebroapp/cerebro-ui/pull/5 to update it and use `@electron/remote`
Soon I will open a PR for `cerebro-basic-apps` but first, cerebro-ui must be published so I can use it

**Comment by dubisdev** [comment]
With the new version of `@cerebroapp/cerebro-ui` app icons are back. Some of them are failing but that's an error with `cerebro-basic-apps`

image

**Comment by dubisdev** [comment]
- [`cerebro-basic-apps` are ready](https://github.com/cerebroapp/cerebro-basic-apps/pull/11#issuecomment-1172912890)

I just need cerebro to create `@cerebroapp` folder in node_modules because it fails if it doesn't exist when installing plugins that start with `@cerebroapp`

image

**Comment by dubisdev** [comment]
Tests are back again 🚀

image

**Comment by dubisdev** [comment]
Hi @oguhpereira I think this PR is ready!

Just three last comments:
- I commented the CI build workflow for macOs as I can not test it. I prefer not releasing an executable if I'm not sure if it will work.
- I added a [section in the readme](https://github.com/dubisdev/cerebro/blob/dev/README.md#publish-a-release) for documenting how to publish a release. I think we could publish this release as the 1.0.0 and make all our dependencies (cerebo-tools, cerebro-ui) match the mayor version with this, so it will be easier to know which versions are compatible.
- I didn't lint all the project files for making the PR easier to review. When you are done, I can run the command and then we merge the PR 🙌

image

**Comment by oguhpereira** [comment]
@dubisdev this adjustment made me very excited, I uploaded a few small commits here and I'm going to merge. thanks for the contribution

**Review by oguhpereira — APPROVED** [review]

**Pull request merged**
